# base image
FROM node:18-alpine

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY package*.json ./

RUN npm install

COPY ./ ./

RUN chmod -R 777 ./node_modules/

# start app
CMD ["npm", "run", "dev"]
