# base image
FROM node:16-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH ./node_modules/.bin:$PATH

# install and cache app dependencies
# COPY package.json ./
COPY package*.json ./

RUN npm install
RUN npm install @vue/cli -g

RUN mkdir ./node_modules/.cache && chmod -R 777 ./node_modules/.cache

COPY ./ ./

# RUN chown -R node /app/node_modules
# USER node

# start app
CMD ["npm", "run", "serve"]
