services:
  # redis-server:
  #   image: redis
  #   # optional: specifiy 6379 default port
  #   ports:
  #     - "6379"
  client:
    restart: always
    # stdin_open: true
    # build: ./
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "8081:8080"
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
