# base image
FROM node:14-alpine

# set working directory
WORKDIR /usr/app

# install and cache app dependencies
COPY package.json ./

RUN npm install

COPY ./ ./

# start app
CMD ["npm", "run", "start"]
