# base image
FROM node:16-alpine

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY package.json ./

RUN npm install

COPY ./ ./

RUN chown -R node /app/node_modules
USER node

# start app
CMD ["npm", "run", "start"]
